### ISSUE TITLE
code idiot

### ISSUE THREAD

**Issue by N0v0cain3** [vishal-1408/Simple-Blog-Web-Application#1]

**Comment by vishal-1408** [comment]
Code under progress idiot! Sent from Mail for Windows 10 From: Shivam MehtaSent: 25 May 2020 21:51To: vishal-1408/Simple-Blog-Web-ApplicationCc: SubscribedSubject: [vishal-1408/Simple-Blog-Web-Application] code idiot (#1) —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
